### ISSUE TITLE
Hello JavaScript Planning Committee

### ISSUE THREAD

**Issue by mikelew42** [tc39/agendas#272]
My name is Michael Lewis.  I live in Aurora, Illinois, and I'd like to get involved in these discussions.

From reading the ECMA website, it appears I have to be a member, fill out a bunch of paper work, and actually attend in-person.  This is not possible.  So, maybe you can further explain in what capacity I can participate?

You could consider myself an intermediate JavaScript developer.  I haven't been following every new proposal, and I'll be of little assistance when discussing JavaScript [[internals]].

However, where I can help, is with the overall developer experience.  I feel like the web is a broken place, where only the elite (professionals who have time to read each other's blogs all day) are capable of truly understanding the changing landscape.

The JavaScript language is evolving at an increasing rate, especially with Babel and transpiling thrown into the mix.  Communicating this committee's long term vision to the public is very important, and it's not happening.  

Currently, you have to sign up for the right mailing lists, read all the blog posts, and really spend a lifetime digging into the details to make sense of it.

It's important to bring it all back to the newbies.  Let's distill this complex vision into a simpler form, and help everyone catch up.

**Comment by TejasQ** [comment]
I'd also like in on this party.

**Comment by TiddoLangerak** [comment]
Not a member of the TC, but to save them some work: [here's](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) the document about contributing to the ecmascript standard. The TL;DR is that as a non-TC member, the place to discuss new features is the [ES discuss mailinglist](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md). Existing proposals are listed in the [ecma262 repo](https://github.com/tc39/ecma262), and since most of them are in Github repos you can easily follow & contribute to specific proposals there.

**Comment by littledan** [comment]
Thanks for those pointers, @TiddoLangerak . I think we need to do more though. I put a topic on the agenda for this coming meeting to discuss improving inclusion.

**Comment by TejasQ** [comment]
@littledan, that'd be awesome. 🎉

**Comment by littledan** [comment]
Also, see the new [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) which describes how you can get involved today.

**Comment by ljharb** [comment]
This appears addressed :-)
